Repository Ayush-projects/chords, pull requests merged in 2021-03, with the labels that each got.

#20 added contributing.md
  contributing.md
Labels: Level0, documentation, gssoc21

#24 Readme.md updated a status bar has been updated
  README.md
Labels: Level0, documentation, gssoc21

#22 Frontend Flowchart details Added
  README.md
Labels: Level0, documentation, gssoc21

#34 Font style changed
  Frontend/musicPlayer.html
  Frontend/style.css
Labels: Level0, gssoc21

#38 Added Contributor
  README.md
Labels: Level0, documentation, gssoc21

#37 Code of Conduct added
  code_of_conduct.md
Labels: Level0, documentation, gssoc21

#48 Adding comments and line breaks in the front end code
  Frontend/index.html
  Frontend/musicPlayer.html
  Frontend/musicPlayerScript.js
  Frontend/script.js
  Frontend/style.css
Labels: Level0, documentation, gssoc21

#47 [QA] Added Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Level0, gssoc21

#45 Volume control functionality added
  Frontend/musicPlayer.html
  Frontend/musicPlayerScript.js
  Frontend/style.css
Labels: Level3, gssoc21

#51 Visuals corrected
  Frontend/musicPlayer.html
  Frontend/musicPlayerScript.js
Labels: Level1, gssoc21

#57 Corrected a typo in HowToContribute.md
  Documentation/HowToContribute.md
Labels: Level0, gssoc21

#56 Fixed typo in HowToContribute.md
  Documentation/HowToContribute.md
Labels: Level0, gssoc21

#54 [feat] Add : Gssoc label workflow
  .github/workflows/autoLabel.yml
Labels: Level1, gssoc21

#61 [GSSoC'21] Creating the footer #18
  Frontend/Footer/assests/52379890.jpg
  Frontend/Footer/assests/Main-Logo.png
  Frontend/Footer/footer.html
  Frontend/Footer/style.css
Labels: Level0, gssoc21

#60 [feat] Gssoc label workflow
  .github/workflows/autoLabel.yml
Labels: Level0, gssoc21

#63 Installation or setup chrome extension document file
  Documentation/FrontEndSetup.md
Labels: Level0, gssoc21

#64 Securing of website[ #52 Fixed ]
  Backend/Audio-Stream/music-stream.js
  Backend/Audio-Stream/package-lock.json
  Backend/Audio-Stream/package.json
  Backend/Audio-Stream/rateLimiter.js
Labels: Level2, gssoc21

#65 Changed the fonts of title track and singer name
  Frontend/style.css
Labels: Level0, gssoc21

#66 Update README.md
  README.md
Labels: Level0, documentation, gssoc21

#69 Removed the error of clicking twice to pause the song during launch
  Frontend/musicPlayer.html
  Frontend/musicPlayerScript.js
Labels: Level2, bug, gssoc21

#70 Dev2 sushi
  Backend/Audio-Stream/.vscode/settings.json
  Frontend/content.js
  Frontend/manifest.json
Labels: Level3, enhancement, gssoc21

#71 Adding gradient and mouse mover over
  Frontend/musicPlayerScript.js
  Frontend/style.css
Labels: Level1, gssoc21
